title: Digital Belajar - Dart Flutter
description: Repositori catatan belajar Dart-Flutter
domain: digital-belajar.github.io
url: http://digital-belajar.github.io/dart-flutter
github_username:  digital-belajar

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
